export default {
    LISTING_RECEIVED: 'LISTING_RECEIVED',
    DETAILS_RECEIVED: 'DETAILS_RECEIVED',
    DETAILS_LOADING: 'DETAILS_LOADING',
    PROFILE_RECEIVED: 'PROFILE_RECEIVED',
    SALE_ITEMS_RECEIVED: 'SALE_ITEMS_RECEIVED',
    LIKES_RECEIVED: 'LIKES_RECEIVED',
    LOGGED_IN: 'LOGGED_IN',
}